language: go
go:
- 1.7
sudo: false
addons:
  postgresql: '9.5'
services:
- postgres
- docker
env:
  matrix:
  - LIBRDKAFKA_VERSION=0.9.2.x
  - LIBRDKAFKA_VERSION=master
cache:
  directories:
  - "$HOME/.cache/librdkafka"
before_install:
- sudo /bin/bash ./travis.sh
before_script: make setup-ci
script: make test
