language: go
go:
- 1.7
- 1.8
sudo: false
addons:
  postgresql: '9.5'
services:
- postgres
- docker
env:
  matrix:
  - LIBRDKAFKA_VERSION=v0.9.5
  - LIBRDKAFKA_VERSION=master
cache:
  directories:
  - "$HOME/.cache/librdkafka"
before_install:
- sudo /bin/bash ./travis.sh
before_script: make setup-ci
script: make test
